### ISSUE TITLE
Print SQL function

### ISSUE THREAD

**Issue by shmish111** [mfwgenerics/koala#40]
Is there a function to print the SQL that will be run? Sometimes it's difficult to understand exactly what you did and you want to play with the SQL in a database client etc.

**Comment by mfwgenerics** [comment]
Hi @shmish111, sorry about the delay getting back to you here.

If you are using MySQL or H2 modules, there are `generateH2Sql` and `generateMysqlSql` methods available for all statements and queries. [Here is an implementation](https://github.com/mfwgenerics/koala/blob/0d6104fd7b2da1df8686c421405f0f3251f1e7a7/postgres/src/main/kotlin/io/koalaql/postgres/PerformableSqls.kt) for Postgres which I'll merge into the next release with some documentation. I'll leave this issue open until then.

Usage example:

```kotlin
val generated: CompiledSql? = MyTable
    .where(MyTable.id eq 1)
    .generateMysqlSql()

println(generated)
```

Output:

```text
SELECT T0.`id` c0
, T0.`firstName` c1
, T0.`lastName` c2
FROM `MyTable` T0
WHERE T0.`id` = ?
(1): int
```

By default this shows the generated parameterized SQL + value type parameter pairs at the bottom. You can print the SQL without the values with:

```kotlin
println(generated?.parameterizedSql)
```

Output:

```text
SELECT T0.`id` c0
, T0.`firstName` c1
, T0.`lastName` c2
FROM `MyTable` T0
WHERE T0.`id` = ?
```

The generated `CompiledSql` is nullable because there are some rare QoL cases where a Koala query is a no-op for what would otherwise be invalid SQL. E.g. when attempting to generate an insert with an empty values clause.

**Comment by eleleung** [comment]
@shmish111 you could try this if you haven't already figured it out, pass in the `JdbcDataSource` into `generateSql(db)` before the `perform()`. I'm pretty sure I've done this before to get the compiled query and then used it directly in pgAdmin. There might be some nuance I'm not aware of with doing it this way but Damo will say if there is :)

```
  val sql = TestTable
      .where(TestTable.nullableField.isNull())
      .generateSql(db)
```

**Comment by shmish111** [comment]
Thanks heaps guys
